openapi: 3.1.0
info:
  title: Roan Assistant API
  description: Access Gmail, Calendar, Drive, Tasks, and Contacts for Zädi using a unified API.
  version: '1.0.0'
servers:
  - url: https://web-production-cf55.up.railway.app
paths:
  /:
    get:
      operationId: healthCheck
      summary: Health check route
      responses:
        '200':
          description: OK
  /calendar/all:
    get:
      operationId: getCalendarEvents
      summary: Get upcoming calendar events
      responses:
        '200':
          description: Successful response
  /gmail/threads:
    get:
      operationId: getGmailThreads
      summary: Get Gmail threads
      responses:
        '200':
          description: Successful response
  /gmail/send:
    post:
      operationId: sendEmail
      summary: Send an email
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                to:
                  type: string
                subject:
                  type: string
                body:
                  type: string
      responses:
        '200':
          description: Email sent
  /drive/files:
    get:
      operationId: listDriveFiles
      summary: List files in Google Drive
      responses:
        '200':
          description: Successful response
  /drive/upload:
    post:
      operationId: uploadDriveFile
      summary: Upload a file to Drive
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                file_name:
                  type: string
                file_path:
                  type: string
      responses:
        '200':
          description: Upload successful
  /tasks/all:
    get:
      operationId: getAllTasks
      summary: Get all Google Tasks
      responses:
        '200':
          description: Successful response
  /tasks/add:
    post:
      operationId: addTask
      summary: Add a new task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                tasklist_id:
                  type: string
                task:
                  type: object
      responses:
        '200':
          description: Task added
  /contacts/search:
    post:
      operationId: searchContacts
      summary: Search contacts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
      responses:
        '200':
          description: Successful response
  /contacts/create:
    post:
      operationId: createContact
      summary: Create a contact
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                contact:
                  type: object
      responses:
        '200':
          description: Contact created
  /contacts/update:
    put:
      operationId: updateContact
      summary: Update a contact
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                resourceName:
                  type: string
                update:
                  type: object
      responses:
        '200':
          description: Contact updated
  /contacts/delete:
    delete:
      operationId: deleteContact
      summary: Delete a contact
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                resourceName:
                  type: string
      responses:
        '200':
          description: Contact deleted
